version: '2.0'

# notes
# clean up volumes if parameters and cofigs not taking effect
# on first execution the files with extensions .sh, .sql and .sql.gz located at /docker-entrypoint-initdb.d will executed (in container)

services:

  # master
  mariadb-galera-0:
    container_name: galera_master
    build:
      context: ./mariadb_galera_0
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera_cluster
      - MARIADB_GALERA_MARIABACKUP_USER=mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=mariabackup_password
      - MARIADB_ROOT_PASSWORD=pis12345
      - MARIADB_USER=zubair.patel
      - MARIADB_PASSWORD=pis12345
      - MARIADB_DATABASE=main
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=replication_password
    volumes:
      - 'mariadb_galera_data_0:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  # node 1
  mariadb-galera-1:
    container_name: galera_node_1
    image: docker.io/bitnami/mariadb-galera:10.6
    ports:
      - '3307:3306'
    command:
      - bash
      - -ec
      - |
          # Wait in seconds to guarantee creation order
          echo 'Sleeping before start'
          sleep 30
          exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera_cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-0:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=mariabackup_password
      - MARIADB_ROOT_PASSWORD=pis12345
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=replication_password
    volumes:
      - 'mariadb_galera_data_1:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      start_period: 20s
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - mariadb-galera-0
    
  # node 2
  mariadb-galera-2:
    container_name: galera_node_2
    image: docker.io/bitnami/mariadb-galera:10.6
    ports:
      - '3308:3306'
    command:
      - bash
      - -ec
      - |
          # Wait in seconds to guarantee creation order
          echo 'Sleeping before start'
          sleep 60
          exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera_cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-0:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=mariabackup_password
      - MARIADB_ROOT_PASSWORD=pis12345
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=replication_password
    volumes:
      - 'mariadb_galera_data_2:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      start_period: 20s
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - mariadb-galera-1

volumes:
  mariadb_galera_data_0:
    driver: local
  mariadb_galera_data_1:
    driver: local
  mariadb_galera_data_2:
    driver: local